# Generated by Django 3.0.8 on 2020-07-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rescue_time_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescue_time_query',
            name='author',
        ),
    ]
